Initial model creation
sarajcev/Seminar pull request #7
Opened 2020-09-23 18:33 UTC by antunmeg

2020-09-24 07:12 UTC, sarajcev requested changes

2020-09-24 07:12 UTC, sarajcev commented on model.ipynb
> +    "y = df['PV'] # Labels"
Ovo kako ste napravili matrice X i y nije analiza vremenskih serija (time-series model). Ovo je obična regresija (multiple regression). Treba prvo od vremenskih nizova podataka napraviti features (time-shift, diff, encode, etc.).

2020-09-24 07:12 UTC, sarajcev commented on model.ipynb
> +    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)"
Treba još razmisliti kako podijeliti podatke, s obzirom da je riječ o vremenskim serijama. Kako će random shuffle utjecati na vremenski niz podataka? Mislim da običan `train_test_split` neće ovdje biti dobar.

2020-09-24 07:12 UTC, sarajcev commented on model.ipynb
> +    "rfr_gs = GridSearchCV(estimator=RandomForestRegressor(criterion='mse'),\n",
Možemo krenuti s RandomForest za početak.

2020-09-24 08:29 UTC, sarajcev requested changes

2020-09-24 08:29 UTC, sarajcev commented on model.ipynb
> +    "pv = pv.resample('15min').mean()"
Resample vremenske serije na rezoluciju od 15-min. Ako se bude radilo satno predviđanje (single-step ahead hourly forecast) mislim da bi bilo puno jednostavnije raditi sa podacima koji imaju satnu rezoluciju?

2020-09-24 08:31 UTC, sarajcev requested changes
Napravio sam pregled ovoga što ste do sada napravili i stavio neke komentare kroz koje bi trebalo proći.

2020-10-02 11:35 UTC, sarajcev commented
Evo samo za primjer funkcija koja generira features iz vremenskih serija. Mogu se dodati još neka druga obilježja s obzirom na karakteristike vremenskih serija. Uglavnom, na ovoj se bazi može dalje graditi.

```python
def engineer_features(dataframe, copy_data=True, resample=True):
    if copy_data:
        df = dataframe.copy()
    if resample:
        df = df.resample('1H').mean()
    
    # Engineer features from time-series data
    for col in df.columns:
        for i in range(1,25):
            # Shift data by lag of 1 to 24 hours
            df[col+'_{:d}h'.format(i)] = df[col].shift(periods=i)  # time-lag
        df[col+'_diff'] = df[col].diff()  # first-difference
    
    # Hour-of-day indicators with cyclical transform
    dayhour_ind = df.index.hour
    df['hr_sin'] = np.sin(dayhour_ind*(2.*np.pi/24))
    df['hr_cos'] = np.cos(dayhour_ind*(2.*np.pi/24))
    
    # Month indicators with cyclical transform
    month_ind = df.index.month
    df['mnth_sin'] = np.sin((month_ind-1)*(2.*np.pi/12))
    df['mnth_cos'] = np.cos((month_ind-1)*(2.*np.pi/12))
    
    # Encoding sunshine hours
    sun_ind = df['PV'] > 0.
    df['sun'] = sun_ind.astype(int)    

    # Drop rows with NaN values
    df.dropna(inplace=True)

    return df
```

2020-10-02 13:29 UTC, sarajcev commented
**Pipeline**: SelectKbest + RandomForestRegressor uz RandomizedSearchCV (TimeSeriesSplit cross-validation) za **istovremenu** redukciju featuresa i optimizaciju hyper-parametara regresora:

```python
# Pipeline: SelectKBest and RandomForest
# SelectKBest is used for features reduction
selectbest = SelectKBest(score_func=mutual_info_regression, k='all')
forest = RandomForestRegressor(criterion='mse')
# Creating a pipeline
pipe = Pipeline(steps=[('kbest', selectbest), ('forest', forest)])
# Parameters of pipeline for the randomized search with cross-validation
param_dists = {'kbest__k': stats.randint(low=32, high=128), 
               'forest__n_estimators': stats.randint(low=200, high=1000),
               'forest__max_depth': [1, 3, 5, None]}
NITER = 100  # number of random search iterations
time_start = timeit.default_timer()
search = RandomizedSearchCV(estimator=pipe, param_distributions=param_dists, 
                            cv=TimeSeriesSplit(n_splits=3),
                            scoring='neg_mean_squared_error',
                            n_iter=NITER, refit=True, n_jobs=-1)
search.fit(X_train, y_train)
time_end = timeit.default_timer()
time_elapsed = time_end - time_start
print('Execution time (hour:min:sec): {}'.format(str(dt.timedelta(seconds=time_elapsed))))
print('Best parameter (CV score = {:.3f}):'.format(search.best_score_))
print(search.best_params_)
```

Ovo može služiti kao baza modela za daljnja razmatranja.

2020-10-02 13:32 UTC, sarajcev commented
@antunmeg možeš pogledati primjere koda iz prethodna dva komentara (kao bazu za model). Nedostaje samo `train_test_split` koji treba implementirati tako da zadrži vremenski slijed podataka (bez random shuffle).

2020-10-05 18:21 UTC, antunmeg commented on model.ipynb
> +    "y = df['PV'] # Labels"
Razumijem!

2020-10-05 18:24 UTC, antunmeg commented
> Evo samo za primjer funkcija koja generira features iz vremenskih serija. Mogu se dodati još neka druga obilježja s obzirom na karakteristike vremenskih serija. Uglavnom, na ovoj se bazi može dalje graditi.
> 
> ```python
> def engineer_features(dataframe, copy_data=True, resample=True):
>     if copy_data:
>         df = dataframe.copy()
>     if resample:
>         df = df.resample('1H').mean()
>     
>     # Engineer features from time-series data
>     for col in df.columns:
>         for i in range(1,25):
>             # Shift data by lag of 1 to 24 hours
>             df[col+'_{:d}h'.format(i)] = df[col].shift(periods=i)  # time-lag
>         df[col+'_diff'] = df[col].diff()  # first-difference
>     
>     # Hour-of-day indicators with cyclical transform
>     dayhour_ind = df.index.hour
>     df['hr_sin'] = np.sin(dayhour_ind*(2.*np.pi/24))
>     df['hr_cos'] = np.cos(dayhour_ind*(2.*np.pi/24))
>     
>     # Month indicators with cyclical transform
>     month_ind = df.index.month
>     df['mnth_sin'] = np.sin((month_ind-1)*(2.*np.pi/12))
>     df['mnth_cos'] = np.cos((month_ind-1)*(2.*np.pi/12))
>     
>     # Encoding sunshine hours
>     sun_ind = df['PV'] > 0.
>     df['sun'] = sun_ind.astype(int)    
> 
>     # Drop rows with NaN values
>     df.dropna(inplace=True)
> 
>     return df
> ```
> 
> Ova funkcija vrati oko tristotinjak featuresa, koji se onda dalje mogu automatski reducirati ostavljajući najvažnije.

Shvatio sam logiku iza ovoga

2020-10-05 18:32 UTC, antunmeg commented on model.ipynb
> +    "pv = pv.resample('15min').mean()"
Slažem se

2020-10-05 18:42 UTC, antunmeg commented on model.ipynb
> +    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)"
Mogu za početak staviti parametar **shuffle=False** pa naknadno provjerimo kako utječe promjenom?

2020-10-05 19:56 UTC, antunmeg commented
> **Pipeline**: SelectKbest + RandomForestRegressor uz RandomizedSearchCV (TimeSeriesSplit cross-validation) za **istovremenu** redukciju featuresa i optimizaciju hyper-parametara time-series regresora:
> 
> ```python
> # Pipeline: SelectKBest and RandomForest
> # SelectKBest is used for features reduction
> selectbest = SelectKBest(score_func=mutual_info_regression, k='all')
> forest = RandomForestRegressor(criterion='mse')
> # Creating a pipeline
> pipe = Pipeline(steps=[('kbest', selectbest), ('forest', forest)])
> # Parameters of pipeline for the randomized search with cross-validation
> param_dists = {'kbest__k': stats.randint(low=32, high=128), 
>                'forest__n_estimators': stats.randint(low=200, high=1000),
>                'forest__max_depth': [1, 3, 5, None]}
> NITER = 100  # number of random search iterations
> time_start = timeit.default_timer()
> search = RandomizedSearchCV(estimator=pipe, param_distributions=param_dists, 
>                             cv=TimeSeriesSplit(n_splits=3),
>                             scoring='neg_mean_squared_error',
>                             n_iter=NITER, refit=True, n_jobs=-1)
> search.fit(X_train, y_train)
> time_end = timeit.default_timer()
> time_elapsed = time_end - time_start
> print('Execution time (hour:min:sec): {}'.format(str(dt.timedelta(seconds=time_elapsed))))
> print('Best parameter (CV score = {:.3f}):'.format(search.best_score_))
> print(search.best_params_)
> ```
> 
> Ovo može služiti kao baza modela za daljnja razmatranja.

Ovo sam simulirao, rezultat je sljedeći:
Execution time (hour:min:sec): 0:13:20.189639
Best parameter (CV score = -0.001):
{'forest__max_depth': None, 'forest__n_estimators': 687, 'kbest__k': 33}

Jasno mi je da sada trebam kao parametre Random Forest Regressora staviti vrijednosti max_depth=None i n_estimators=687. Međutim, ne razumijem što točno znači ovaj broj 33. Ako imam 290 featuresa vjerojatno ovo govori da je odabranim kriterijem najbolje koristiti 33 featuresa, ali kojih 33? Treba mi informacija o nazivu featuresa da bi mogao izdvojiti najvažnije.

2020-10-06 05:53 UTC, sarajcev commented on model.ipynb
> +    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)"
Može.

2020-10-06 06:05 UTC, sarajcev requested changes
Kolega @antunmeg pogledajte malo detaljnije kako se koristi `scikit-learn` API, s posebnim naglaskom na `RandomizedSearchCV` i `Pipeline`s.

2020-10-06 06:05 UTC, sarajcev commented on model.ipynb
> +    "rfr = RandomForestRegressor(criterion='mse', max_depth=None, n_estimators=687)\n",
Ovo se ne radi ručno! `rfr = RandomForestRegressor(criterion='mse', **rfr_gs.best_params_)` Ovaj dio sa "**" služi kao tzv. argument unpacking. Sve treba biti automatizirano! Osim toga, korišten je argument `refit=True` kod `RandomizedSearchCV` što znači da `fit` metoda "vrača" najbolji regresor. Pogledajte malo detaljnije kako se koristi `scikit-learn` API. Konačno, `Pipeline` povezuje fazu selekcije najkorisnijih featuresa i treniranje regresora (featuresi će najvjerojatnije biti različiti kako se bude mjenjao vremenski horizont i cijeli sustav stoga mora biti potpuno automatiziran).

2020-10-06 06:05 UTC, sarajcev commented on model.ipynb
> +    "# rfr_gs = GridSearchCV(estimator=RandomForestRegressor(criterion='mse'),\n",
`GridSearchCV` smo zamijenili s `RandomizedSearchCV` koji je učinkovitiji! Ovaj cijeli dio koda je redundantan!

2020-10-06 08:35 UTC, sarajcev commented
Dodao bih u **Pipeline** još jedan preprocessing korak:
```python
# Creating a pipeline
pipe = Pipeline(steps=[('preprocess', 'passthrough'), 
                       ('kbest', selectbest), 
                       ('forest', forest)])
# Parameters of pipeline for the randomized search with cross-validation
param_dists = {'preprocess': [None, StandardScaler()], 
               'kbest__k': stats.randint(low=32, high=128), 
               'forest__n_estimators': stats.randint(low=200, high=1000),
               'forest__max_depth': [1, 3, 5, None]}
```
da vidimo da li `StandardScaler` donosi poboljšanje (biti će automatski odabran ili pak neće).

2020-10-06 10:58 UTC, sarajcev requested changes

2020-10-06 10:58 UTC, sarajcev commented on model.ipynb
> +    "from sklearn.model_selection import RandomizedSearchCV"
Sve `import` naredbe moraju ići na vrh notebooka.

2020-10-06 12:26 UTC, sarajcev commented
@antunmeg Kako sada stvari stoje, model pretpostavlja da postoje dostupni podaci o vremenskoj prognozi za sat unaprijed kada se radi predikcija proizvodnje (hour-ahead single-step forecast). Kako mi radimo *ex-post* validaciju modela, to mi koristimo povijesne podatke i za ovo "predviđanje" vremenske prognoze. Ukoliko ne bi usvojili tu pretpostavku (o dostupnoj vremenskoj prognozi), tada bi trebalo nakon poziva `engineer_features` **eliminirati** sve varijable vezane uz vremensku prognozu `[CD, CM, CU, PREC, RH2m, SNOW, ST, SWD, SWDtop, TT2M, WS100m, WS10m]` i ostaviti samo njihove featurese (time-shift, diff). Time eliminiramo sve informacije o vremenkoj prognozi za sat (unaprijed) za koji radimo predikciju proizvodnje i ona se temelji isključivo na povijesnim podacima (o vremenskoj prognozi i proizvodnji). Model i dalje ostaje statičan.

2020-10-06 12:50 UTC, sarajcev requested changes

2020-10-06 12:50 UTC, sarajcev commented on model.ipynb
> +    "plt.legend();"
Ovaj dio koda zamijeniti sa:
```python
plt.figure(figsize=(12,4.5))
plt.plot(y_test.index, y_preds, label='predictions')
plt.plot(y_test.index, y_test.values, lw=2, label='true values')
plt.legend()
plt.grid(axis='y')
plt.xlabel('Hours')
plt.show()
```

2020-10-09 11:08 UTC, merged